
-- 1. ENUMS & TYPES
DO $$ BEGIN
    CREATE TYPE event_type AS ENUM ('client', 'restaurant');
    CREATE TYPE event_status AS ENUM ('draft', 'confirmed', 'in_progress', 'completed', 'cancelled');
    CREATE TYPE guest_type AS ENUM ('adult', 'minor', 'staff');
    CREATE TYPE menu_type AS ENUM ('standard', 'premium', 'custom');
    CREATE TYPE zone_type AS ENUM ('left', 'right', 'front', 'center');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. HALLS (Saloane)
CREATE TABLE IF NOT EXISTS event_halls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    width_meters NUMERIC(5,2) NOT NULL DEFAULT 20.00, -- Dimensions for grid
    length_meters NUMERIC(5,2) NOT NULL DEFAULT 30.00,
    entry_point_x NUMERIC(5,2), -- Coordinates for "Entrare"
    entry_point_y NUMERIC(5,2),
    dancefloor_x NUMERIC(5,2), -- Coordinates for "Ring Central"
    dancefloor_y NUMERIC(5,2),
    stage_x NUMERIC(5,2),      -- Default Stage position
    stage_y NUMERIC(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Default Halls (Chianti has 3 salons usually)
INSERT INTO event_halls (name, width_meters, length_meters)
VALUES 
('Salon Principal', 20, 30),
('Salon Mic', 15, 20),
('Terasă', 25, 15)
ON CONFLICT DO NOTHING;

-- 3. EVENTS (Dosarul Evenimentului)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- e.g. "Nunta Popescu" or "8 Martie"
    type event_type NOT NULL DEFAULT 'client',
    status event_status NOT NULL DEFAULT 'draft',
    
    -- Scheduling
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    hall_id BIGINT REFERENCES event_halls(id),
    
    -- Rules
    allow_minors BOOLEAN DEFAULT FALSE,
    guest_count_expected INTEGER DEFAULT 0,
    
    -- Commercial
    deposit_amount NUMERIC(10,2) DEFAULT 0,
    total_cost_estimated NUMERIC(10,2) DEFAULT 0,
    
    -- Client Access
    client_name TEXT,
    client_phone TEXT,
    client_email TEXT,
    access_token UUID DEFAULT gen_random_uuid(), -- For Portal Link
    
    -- Operational
    pv_signed BOOLEAN DEFAULT FALSE,
    pv_file_url TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. LAYOUT OBJECTS (Mese, Scena, Obiecte in Sala)
CREATE TABLE IF NOT EXISTS event_layout_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    
    -- Visual Properties
    type TEXT NOT NULL, -- 'table_round_12', 'table_rect_6', 'stage', 'dancefloor', 'presidium'
    label TEXT, -- 'Masa 1', 'Masa Mirilor'
    
    -- Position
    x NUMERIC(5,2) NOT NULL,
    y NUMERIC(5,2) NOT NULL,
    rotation INTEGER DEFAULT 0,
    width NUMERIC(5,2) DEFAULT 1,
    height NUMERIC(5,2) DEFAULT 1,
    
    -- Logic
    zone zone_type, -- Calculated automatically: 'left', 'right', 'front'
    capacity INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. GUESTS (Invitati)
CREATE TABLE IF NOT EXISTS event_guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    
    full_name TEXT NOT NULL,
    type guest_type DEFAULT 'adult',
    
    -- Assignment
    layout_object_id BIGINT REFERENCES event_layout_objects(id) ON DELETE SET NULL, -- Assigned Table
    seat_number INTEGER, -- Optional exact seat
    
    -- Menu Choice
    menu_preference TEXT, -- 'post', 'frupt', 'special'
    notes TEXT, -- Allergies
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. MENU PACKAGES (Definitii Meniuri)
CREATE TABLE IF NOT EXISTS event_menu_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- "Meniu Nunta Premium"
    price NUMERIC(10,2) NOT NULL,
    description TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. MENU ITEMS (Legatura Meniu -> Produse/Retete)
CREATE TABLE IF NOT EXISTS event_menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES event_menu_packages(id) ON DELETE CASCADE,
    
    product_id BIGINT REFERENCES products(id), -- Link to existing products catalogue
    course_type TEXT, -- 'aperitiv', 'fel_principal', 'desert'
    
    quantity_per_guest NUMERIC(5,2) DEFAULT 1
);

-- 8. EVENT STAFF (Echipe)
CREATE TABLE IF NOT EXISTS event_staff_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    
    staff_name TEXT NOT NULL, -- Or link to a user table if exists
    role TEXT NOT NULL, -- 'seful_sala', 'bucatar_sef', 'ospatar'
    
    phone TEXT,
    access_code TEXT -- Simple pin for mobile access if needed
);

-- RLS POLICIES (Simplified for Admin usage primarily)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON events FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE event_halls ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON event_halls FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE event_layout_objects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON event_layout_objects FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE event_guests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON event_guests FOR ALL USING (auth.role() = 'authenticated');

-- Public access for Guest Portal (via Token - simplified)
-- In a real scenario, we'd use a function to check token, but for now we might keep RLS open or specific.
-- We will use a dedicated RPC or Edge Function for the Guest Portal to ensure security.
