
-- 1. EVENT TIMELINE (Desfasurator)
CREATE TABLE IF NOT EXISTS event_timeline_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    
    time_start TIME NOT NULL, -- "18:00"
    activity TEXT NOT NULL, -- "Servire Aperitiv"
    notes TEXT, -- "Atentie la temp"
    status TEXT DEFAULT 'pending', -- pending, done
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STAFF CHECK-IN (Optional, for tracking who worked)
ALTER TABLE event_staff_assignments 
ADD COLUMN IF NOT EXISTS check_in_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS check_out_time TIMESTAMPTZ;

-- 3. CLOSING REPORT (PV)
-- We can store the final report in a JSONB column on events or a separate table if it needs structure.
-- Let's use a separate table for structure.
CREATE TABLE IF NOT EXISTS event_closing_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    
    -- Financials
    total_sales NUMERIC(10,2) DEFAULT 0,
    total_payments_received NUMERIC(10,2) DEFAULT 0,
    tips_amount NUMERIC(10,2) DEFAULT 0,
    
    -- Inventory / Issues
    broken_items_cost NUMERIC(10,2) DEFAULT 0,
    notes TEXT,
    
    -- Signatures (Simple boolean or name for now)
    manager_signed_by TEXT,
    client_signed_by TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE event_timeline_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON event_timeline_items FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE event_closing_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for authenticated users" ON event_closing_reports FOR ALL USING (auth.role() = 'authenticated');
