-- 1. Ensure table exists
CREATE TABLE IF NOT EXISTS inventory_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add 'label' column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='inventory_categories' AND column_name='label') THEN
        ALTER TABLE inventory_categories ADD COLUMN label TEXT;
    END IF;
END $$;

-- 3. Seed Data (Upsert)
INSERT INTO inventory_categories (name, label) VALUES 
('Materii Prime', 'Materii Prime (Ingrediente)'),
('Ambalaje', 'Ambalaje & Consumabile'),
('Bauturi', 'Băuturi (Bar)'),
('Obiecte Inventar', 'Obiecte de Inventar (Veselă/Echipamente)')
ON CONFLICT (name) DO UPDATE 
SET label = EXCLUDED.label;

-- 4. Enable RLS (Safe to re-run)
ALTER TABLE inventory_categories ENABLE ROW LEVEL SECURITY;

-- 5. Policies (Drop first to avoid errors on re-run)
DROP POLICY IF EXISTS "Public read inventory_categories" ON inventory_categories;
CREATE POLICY "Public read inventory_categories" ON inventory_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auth write inventory_categories" ON inventory_categories;
CREATE POLICY "Auth write inventory_categories" ON inventory_categories FOR ALL USING (auth.role() = 'authenticated');
