CREATE TABLE IF NOT EXISTS product_extras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    extra_product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(parent_product_id, extra_product_id)
);

ALTER TABLE product_extras ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public read extras" ON product_extras FOR SELECT USING (true);

-- Allow authenticated (admin) insert/update/delete
CREATE POLICY "Admin manage extras" ON product_extras FOR ALL USING (auth.role() = 'authenticated');
