-- Create admin_logs table
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_name TEXT NOT NULL,
    admin_role TEXT,
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Insert: Allow any authenticated admin (or anon if we rely on app logic, but preferably authenticated)
-- Since our "auth" is custom/local for now (localStorage + Supabase generic client), we might need public insert 
-- IF we are not using Supabase Auth users. 
-- The keys are standard Supabase keys.
-- Let's allow public insert for now to match the admin_users pattern, relies on App Logic security.
CREATE POLICY "Allow public insert to admin_logs" ON admin_logs FOR INSERT WITH CHECK (true);

-- 2. Select: Allow public read (secured by App Login)
CREATE POLICY "Allow public select on admin_logs" ON admin_logs FOR SELECT USING (true);
