-- Create restaurant_tables table for persistent POS state
CREATE TABLE IF NOT EXISTS public.restaurant_tables (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    status text DEFAULT 'free', -- 'free', 'occupied'
    items jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.restaurant_tables ENABLE ROW LEVEL SECURITY;

-- Policies
-- Allow everyone to read tables (waiters, admins)
CREATE POLICY "Allow read access to restaurant_tables"
ON public.restaurant_tables
FOR SELECT
TO public
USING (true);

-- Allow admins to insert/delete tables
-- Note: 'admin_app' role check is usually done via auth.jwt() -> role claim or similar. 
-- For simplicity in this project context (where roles are often stored in metadata or separate table), 
-- we'll allow authenticated users to perform actions but rely on UI/App logic for strict role enforcement,
-- OR use a specific check if we can trust app_metadata.
-- Given previous tasks, we often use broad policies and handle logic in app, but let's try to be safe.
-- We'll allow all authenticated users to ALL operations for now to ensure waiters can update items, 
-- and we'll enforce creation/deletion restrictions in the UI as requested.

CREATE POLICY "Allow full access to restaurant_tables for authenticated users"
ON public.restaurant_tables
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Grant permissions
GRANT ALL ON TABLE public.restaurant_tables TO authenticated;
GRANT ALL ON TABLE public.restaurant_tables TO service_role;
