-- Create Tables for Chianti Project

-- 1. Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text default 'delivery', -- 'delivery' or 'catering'
  sort_order integer default 0
);

-- 2. Products
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  category text, -- storing name for simplicity as per current app logic, or link to id
  image text, -- Application handles base64 or url
  description text,
  weight text,
  ingredients text,
  is_active boolean default true
);

-- 3. Orders
create table public.orders (
  id text primary key, -- Keeping string ID from frontend for now (Date.now()) or switch to UUID/BigInt
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_data jsonb, -- Stores name, address, phone etc.
  items jsonb, -- Stores array of items
  total numeric,
  final_total numeric,
  delivery_cost numeric,
  status text default 'pending', -- pending, preparing, delivering, completed, cancelled
  driver_status text, -- assigned, en_route, delivered
  assigned_driver_id text,
  is_catering boolean default false,
  archived boolean default false
);

-- 4. Inventory
create table public.inventory_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text,
  stock numeric default 0,
  unit text,
  entry_date date
);

create table public.inventory_categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

-- 5. Driver Applications
create table public.driver_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text,
  email text,
  experience text,
  vehicle text,
  status text default 'pending' -- pending, approved, rejected
);

-- Enable Realtime (This is crucial for OrderContext)
alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.products;
alter publication supabase_realtime add table public.categories;
