INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cârnați proaspeți de porc', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cârnați afumați de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cârnați subțiri de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cârnați cabanos de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Salam crud-uscat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Salam fiert-afumat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șuncă presată de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șuncă fiartă de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șuncă afumată de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șuncă crud-uscată (prosciutto) de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Kaiser (piept afumat) de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Bacon feliat de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Bacon cuburi de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pancetta maturată de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mușchi file afumat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mușchi țigănesc de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cotlet afumat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ciolan afumat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Costiță afumată de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Slănină afumată de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Jumări de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șorici pufuleți de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Șorici fiert (ambalat) de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Tobă de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Caltaboș de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sângerete de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Leber de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pate de ficat de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Parizer de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Crenvurști de porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Virșli de porc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Chiftele de porc (semi-preparat)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mini-chiftele de porc (semi-preparat)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mici de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Burger de porc (semi-preparat)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cârnați de grătar condimentați de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ruladă de porc (semi-preparat)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ceafă marinată de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Friptură marinată de porc', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – somon file', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – ton steak', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – cod file', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – doradă eviscerată', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – biban de mare', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – păstrăv întreg', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – șalău', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – crap', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – calcan', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește proaspăt – macrou', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – somon file', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – cod file', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – merluciu (hake) file', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – pollock file', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – pangasius file', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – păstrăv file', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – ton cuburi', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește congelat – mix file pește', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – creveți decorticați', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – creveți cu coajă', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – midii în cochilie', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – midii miez', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – scoici vongole', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – calamar inele', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – calamar tub', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – sepie', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – caracatiță', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de mare congelate – mix fructe de mare', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește (produs) – surimi bastoane', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește (produs) – icre (materie primă)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește (produs) – salată de icre', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește afumat – somon feliat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește afumat – păstrăv', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește afumat – macrou', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pește afumat – hering', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Lapte – integral 3.5%', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Lapte – semi-degresat 1.5%', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Lapte – fără lactoză', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Smântână – fermentată 12%', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Smântână – fermentată 20%', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Smântână – pentru gătit 30%', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Unt – 82% grăsime', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Unt – clarifiat (ghee)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi maturate – parmezan', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi maturate – pecorino', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi maturate – grana padano', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi maturate – gouda maturată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi proaspete – telemea', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi proaspete – brânză de vaci', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi proaspete – ricotta', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi proaspete – mascarpone', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Brânzeturi proaspete – cremă de brânză', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cașcaval – clasic', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cașcaval – afumat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Iaurt – natural', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Iaurt – grecesc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Frișcă – lichidă 30–35%', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Frișcă – spray (produs)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ouă – proaspete (categoria M/L)', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ouă – albuș pasteurizat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe proaspete – mere', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe proaspete – banane', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe proaspete – pere', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe congelate – căpșuni', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe congelate – mango cuburi', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe congelate – mix fructe', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe uscate – stafide', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe uscate – caise', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe uscate – prune', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Citrice – lămâi', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Citrice – portocale', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Citrice – grepfrut', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de pădure – zmeură', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de pădure – afine', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe de pădure – mure', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Făină – albă tip 000', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Făină – albă tip 650', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Făină – integrală', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mălai – extra', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Orez – basmati', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Orez – arborio', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Orez – cu bob rotund', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Paste – spaghetti', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Paste – penne', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Paste – tagliatelle', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pâine – albă feliată', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pâine – rustică', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pâine – baghetă', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pesmet – clasic', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Pesmet – panko', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Aluat – foietaj', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Aluat – pizza', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse de patiserie – croissant (congelat/ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse de patiserie – foietaj sărat (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve legume – roșii cuburi', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve legume – porumb boabe', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve legume – fasole roșie', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve pește – ton bucăți', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve pește – sardine', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Conserve pește – macrou', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sosuri gata preparate – sos bolognese', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sosuri gata preparate – sos curry', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sosuri gata preparate – sos sweet chili', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Murături – castraveți murați', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Murături – gogonele murate', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Murături – varză murată', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semipreparate – cartofi prăjiți prefierți', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semipreparate – nuggets (pui)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semipreparate – șnițel (pui/porc)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Creme și piureuri – piure de roșii', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Creme și piureuri – pastă de ardei', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Creme și piureuri – pastă de usturoi', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sare – fină', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sare – grunjoasă', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Piper – negru măcinat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Piper – boabe', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Boia – dulce', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Boia – iute', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ierburi uscate – oregano', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ierburi uscate – busuioc', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ierburi uscate – cimbru', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mixuri de condimente – pentru grătar', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mixuri de condimente – pentru cartofi', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Condimente exotice – curry', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Condimente exotice – turmeric', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semințe – susan', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semințe – chimen', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semințe – muștar boabe', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ulei vegetal – floarea-soarelui', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ulei vegetal – rapiță', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ulei de măsline – extra virgin', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ulei de măsline – pentru gătit', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Untură – porc', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Margarina – pentru patiserie', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Grăsimi speciale – ulei de susan', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Zahăr alb – cristal', 'Materii Prime', 'kg', 5, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Zahăr brun – cristal', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Miere – polifloră', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Siropuri – arțar', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Siropuri – agave', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Îndulcitori – stevia', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sos tomate – passata', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Sos tomate – concentrat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Maioneză – clasică', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Maioneză – light', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Muștar – clasic', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Muștar – Dijon', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ketchup – clasic', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Dressinguri – Caesar', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Dressinguri – vinaigrette', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Creme culinare – cremă de gătit vegetală', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne congelată – pui (porționat)', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne congelată – porc (tocătură)', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne congelată – vită (tocătură)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Legume congelate – mix legume', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Legume congelate – mazăre', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Legume congelate – fasole verde', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse patiserie congelate – foietaj', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse patiserie congelate – croissant', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Deserturi congelate – înghețată vanilie', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Deserturi congelate – înghețată ciocolată', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Deserturi congelate – lava cake (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Nuci – miez de nucă', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Alune – alune de pădure', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Semințe – floarea-soarelui', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe oleaginoase – migdale', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Fructe oleaginoase – caju', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Toppinguri – fulgi de cocos', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Toppinguri – fulgi de ciocolată', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ciocolată – neagră', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Ciocolată – lapte', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Cacao – pudră', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Esențe – vanilie', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Esențe – rom', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Blaturi – pandișpan (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Creme – cremă de patiserie (bază)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Glazuri – glazură ciocolată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – nuggets', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – crispy strips', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – șnițel (pane)', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – aripioare marinate BBQ', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – aripioare picante (hot wings)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – frigărui (cuburi marinate)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – carne tocată asezonată (chiftele)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – burger (chiftea)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – kebab/gyros fâșii marinate', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – burger (chiftea)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – șnițel (pane)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – rață – confit (pulpe)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – crenvurști', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – crenvurști', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – parizer', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – parizer', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – salam', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – pate de ficat', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – rață – rillettes (pastă)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – cârnați proaspeți', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – cârnați proaspeți', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – șuncă presată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – piept afumat feliat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – piept afumat feliat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – șuncă afumată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – pui – pulpe afumate', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – rață – piept afumat', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – rață – pastramă', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de pasăre – curcan – pastramă', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – burger (chiftea)', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – carne tocată asezonată (chiftele)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – mititei (ready)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – kebab/gyros fâșii marinate', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – frigărui (cuburi marinate)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – steak porționat (antricot)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – steak porționat (vrăbioară)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – gulas (cuburi)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – pulled beef (gătit, sous-vide/ready)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – salam crud-uscat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – salam fiert-afumat', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – pastramă (feliată)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – șuncă presată (feliată)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – parizer', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – crenvurști', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – pastramă afumată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – mușchi afumat (feliat)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vită – costiță afumată (beef ribs)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – tocătură asezonată', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – chiftele (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – burger (chiftea)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – frigărui (cuburi marinate)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – cotlet porționat (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – pulpă feliată pentru cuptor (ready)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – pastramă (crudă, gata de gătit)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – cârnați proaspeți', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – pastramă afumată', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de miel – cârnați afumați', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – mistreț – tocătură', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – mistreț – cârnați proaspeți', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – mistreț – pulpă cuburi (gulaș)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – cerb – pulpă cuburi (gulaș)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – cerb – steak porționat', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – căprioară – pulpă cuburi', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – iepure – tranșat (ready)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – rață sălbatică – tranșată (ready)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – salam crud-uscat', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – pastramă (feliată)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Carne de vânat – pate (produs)', 'Materii Prime', 'kg', 1, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – cârnați proaspeți (mix carne)', 'Materii Prime', 'kg', 4, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – cârnați afumați (mix carne)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – salam crud-uscat (mix carne)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – salam fiert-afumat (mix carne)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – crenvurști (mix carne)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – parizer (mix carne)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – șuncă presată (mix carne)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Mezeluri mix – pate (mix carne)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – bacon feliat (mix)', 'Materii Prime', 'kg', 3, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – piept afumat (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – cotlet afumat (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – ciolan afumat (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – costiță afumată (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – pastramă afumată (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;
INSERT INTO inventory_items (name, category, unit, min_stock_alert, is_asset) VALUES ('Produse afumate mix – mușchi afumat (mix)', 'Materii Prime', 'kg', 2, false) ON CONFLICT (name) DO NOTHING;

